# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1857f2241edff09b0ce6a8e3b3030e38"
application_url = "https://example.com"
embedded = true
name = "CROOKS Partner Hub"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory,write_orders,write_merchant_managed_fulfillment_orders,read_discounts,read_locations,read_fulfillments,write_discounts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-10"
