#!/usr/bin/env python3
"""Digest a quarantined directory: recognise, scan and decompose it, relate it to CLIVE, and
say what CLIVE proposes to take from it.

    python scripts/digest.py PATH --origin ORIGIN [--origin-kind directory]
        [--pinned-ref REF] [--licence L] [--store DIR] [--report FILE]
        [--no-relate | --self-model-root ROOT] [--self]

PATH is the quarantined copy, already in place: this reads it and never executes, imports or
installs anything in it, and uses no network. The content digest is computed from the tree
itself (pipeline.tree_digest: sorted relative paths and bytes, symbolic links named and never
followed, bounded) and pins the Source when --pinned-ref is not given. With --store the source,
artifact, units, findings and proposals are written to that digest store; the same intake
digested again (same origin, kind, pinned reference and licence) keeps the time it was first
taken, and the ledger keeps each proposal once, so a re-run changes nothing. With --report the
Markdown report is written to FILE.

The Units are related to CLIVE's self-model (app/digest/selfmodel.py), generated by default
from the repository this script belongs to; --self-model-root generates it from another
checkout of CLIVE instead, and --no-relate digests without it: no relations, no proposals.
--self digests CLIVE's own repository as itself: everything is related and traced to the
product memory (the why-index, and where code and memory have drifted apart), and nothing is
proposed.

One line is printed: the artifact, its Units, its findings by severity, its kinds and, when it
was related, its relations by kind and its proposals by target.

Exit status: 0 digested; 2 blocked in quarantine by a block-severity finding, before
decomposition; 1 could not digest (bad arguments, not a directory, too large to pin, a
different record already stored under this artifact's id, or a file that cannot be written).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# The script runs standalone (python scripts/digest.py); it must find the app package.
APP_ROOT = Path(__file__).resolve().parent.parent
if str(APP_ROOT) not in sys.path:
    sys.path.insert(0, str(APP_ROOT))

from app.digest.model import (  # noqa: E402
    ABSORPTION_TARGETS,
    ORIGIN_KINDS,
    SEVERITIES,
    Source,
    utc_now,
)
from app.digest.pipeline import DigestResult, digest, tree_digest  # noqa: E402
from app.digest.propose import needs_owner  # noqa: E402
from app.digest.relate import RELATIONS  # noqa: E402
from app.digest.report import render  # noqa: E402
from app.digest.selfmodel import build_self_model  # noqa: E402
from app.digest.store import ArtifactConflict, DigestStore  # noqa: E402

DIGESTED = 0
FAILED = 1
BLOCKED = 2


class _Parser(argparse.ArgumentParser):
    """Bad arguments exit 1, so that 2 always means blocked."""

    def error(self, message: str) -> None:  # type: ignore[override]
        self.print_usage(sys.stderr)
        self.exit(FAILED, f"{self.prog}: error: {message}\n")


def _parser() -> argparse.ArgumentParser:
    parser = _Parser(description="Digest a quarantined directory into Units, findings, relations, "
                                 "proposals and a report.")
    parser.add_argument("path", type=Path, help="the quarantined directory to digest")
    parser.add_argument("--origin", required=True, help="where the artifact came from: a URL or path, as given")
    parser.add_argument("--origin-kind", default="directory", choices=ORIGIN_KINDS)
    parser.add_argument("--pinned-ref", help="commit SHA or other pin (default: the content digest)")
    parser.add_argument("--licence", help="the artifact's licence, when known")
    parser.add_argument("--store", type=Path, help="digest store directory to write to")
    parser.add_argument("--report", type=Path, help="file to write the Markdown report to")
    relating = parser.add_mutually_exclusive_group()
    relating.add_argument("--no-relate", action="store_true",
                          help="do not relate the Units to CLIVE's self-model, and propose nothing")
    relating.add_argument("--self-model-root", type=Path,
                          help="the CLIVE repository to generate the self-model from "
                               "(default: the one this script belongs to)")
    parser.add_argument("--self", dest="itself", action="store_true",
                        help="the artifact is CLIVE itself: trace it to the product memory and "
                             "propose nothing")
    return parser


def summary(result: DigestResult) -> str:
    counts = {severity: 0 for severity in SEVERITIES}
    for finding in result.findings:
        counts[finding.severity] += 1
    by_severity = ", ".join(f"{severity} {counts[severity]}" for severity in reversed(SEVERITIES))
    line = (
        f"{'blocked' if result.blocked else 'digested'} {result.artifact.id}: "
        f"{len(result.artifact.units)} units; findings: {by_severity}; "
        f"kinds: {', '.join(result.artifact.kinds) or 'none'}"
    )
    if not result.related:
        return line + "; not related"
    relations = {name: 0 for name in RELATIONS}
    for relation in result.relations:
        relations[relation.relation] += 1
    if result.purpose == "self" and result.trace is not None:
        trace = result.trace
        return (f"{line}; relations: {', '.join(f'{name} {n}' for name, n in relations.items())}; "
                f"self: {trace.traced_code_units} of {trace.code_units} code units traced to "
                f"memory, {trace.shipped_without_code_count} shipped feature(s) with no code found")
    targets: dict[str, int] = {}
    for proposal in result.proposals:
        targets[proposal.target] = targets.get(proposal.target, 0) + 1
    by_target = ", ".join(f"{t} {targets[t]}" for t in ABSORPTION_TARGETS if t in targets) or "none"
    owner = sum(1 for proposal in result.proposals if needs_owner(proposal))
    return (
        f"{line}; relations: {', '.join(f'{name} {n}' for name, n in relations.items())}; "
        f"proposals: {by_target} ({owner} need the owner)"
    )


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    if args.itself and args.no_relate:
        print("digest: --self relates the artifact to CLIVE, so it cannot go with --no-relate",
              file=sys.stderr)
        return FAILED
    try:
        pinned = tree_digest(args.path)
        source = Source(
            origin=args.origin, origin_kind=args.origin_kind, pinned_ref=args.pinned_ref or pinned,
            licence=args.licence, taken_at=utc_now(), content_digest=pinned,
        )
        store = DigestStore(args.store) if args.store is not None else None
        if store is not None and store.has(source.artifact_id):
            stored = store.load(source.artifact_id).source
            if _same_intake(stored, source):
                source = stored
        self_model = None
        if not args.no_relate:
            root = args.self_model_root if args.self_model_root is not None else APP_ROOT
            if not root.is_dir():
                raise NotADirectoryError(f"the self-model root {root} is not a directory")
            self_model = build_self_model(root)
        result = digest(args.path, source, store, self_model=self_model,
                        purpose="self" if args.itself else "absorb")
        if args.report is not None:
            args.report.parent.mkdir(parents=True, exist_ok=True)
            args.report.write_text(render(result), encoding="utf-8")
    except ArtifactConflict as error:
        print(f"digest: {error}", file=sys.stderr)
        return FAILED
    except (OSError, ValueError) as error:
        print(f"digest: {type(error).__name__}: {error}", file=sys.stderr)
        return FAILED
    print(summary(result))
    return BLOCKED if result.blocked else DIGESTED


def _same_intake(stored: Source, source: Source) -> bool:
    return (stored.origin, stored.origin_kind, stored.pinned_ref, stored.licence) == (
        source.origin, source.origin_kind, source.pinned_ref, source.licence,
    )


if __name__ == "__main__":
    sys.exit(main())
