"""Generated files are the loop's job, not the builder's (OWNER_DECISIONS_2026-09-30, "go").

On 30 September six of seven builds the owner filed were blocked by one test,
``tests/test_tool_matrix.py::test_the_checked_in_document_is_the_generated_one``: any new test file
changes the generated ``docs/phase4/TOOL_MATRIX.md``, and a builder may not regenerate it. These tests
drive the real dispatcher, kernel, git and worker process (the dispatcher tests' fake ``claude``) over a
repository whose base declares a small generator in ``crooks-assistant/config/generated_files.json``:
``tools/gen_index.py`` writes ``docs/INDEX.md``, the sorted list of files under ``pkg/``, which lies
outside the objective's scope (``pkg``), exactly as the tool matrix lies outside a build's.

The declaration is read from the task's base commit and never from the candidate; generators run through
the dispatcher's check runner (the namespace sandbox in production, the tree runner double here); only
declared outputs come back, as the loop's own commit; a generator that changes anything else blocks; a
declared output is never a protected path. The last test runs the repository's own declaration.
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

from app.orchestrator import objectives as objectives_module
from app.orchestrator.contracts import TaskKind, TaskStatus
from app.orchestrator.lifecycle import EventKind
from app.orchestrator.objectives import PROTECTED_PATHS, Check
from tests.test_engineering_dispatcher import OBJ, World, _git, review

DECLARATION = "crooks-assistant/config/generated_files.json"   # the path the dispatcher reads, at the base
INDEX = "docs/INDEX.md"
GENERATOR = '''import pathlib
root = pathlib.Path(".")
names = sorted(p.relative_to(root).as_posix() for p in (root / "pkg").rglob("*") if p.is_file())
(root / "docs").mkdir(exist_ok=True)
(root / "docs" / "INDEX.md").write_text("# pkg index\\n" + "".join(f"- {n}\\n" for n in names))
'''
INDEX_BASE = "# pkg index\n- pkg/hello.txt\n"


def declaration(*generators: dict) -> str:
    return json.dumps({"schema": "clive.generated_files.v1", "generators": list(generators)}, indent=2)


PKG_INDEX = {"name": "pkg-index", "argv": ["{python}", "tools/gen_index.py"], "cwd": ".", "outputs": [INDEX]}


def commit_base(w: World, files: dict[str, str], message: str = "declare the loop's generators") -> str:
    """Commit ``files`` on main and make that commit the base the objective starts from."""
    for rel, content in files.items():
        path = w.repo / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    _git(w.repo, "add", "-A")
    _git(w.repo, "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-q", "-m", message)
    w.base = _git(w.repo, "rev-parse", "HEAD")
    return w.base


def generated_world(tmp_path: Path, *, generators=(PKG_INDEX,), extra: dict | None = None, **kw) -> World:
    w = World(tmp_path, **kw)
    commit_base(w, {DECLARATION: declaration(*generators), "tools/gen_index.py": GENERATOR, INDEX: INDEX_BASE,
                    **(extra or {})})
    return w


ADD_TEST_FILE = {"edits": [["pkg/hello.txt", "hello\n"], ["pkg/test_new.py", "def test_new():\n    pass\n"]]}


# ---------------------------------------------------------------- the loop regenerates and commits

def test_a_candidate_that_adds_a_test_file_gets_its_generated_file_regenerated_and_committed_by_the_loop(tmp_path):
    index_check = Check(name="index", argv=("grep", "-qxF", "-e", "- pkg/test_new.py", INDEX))
    w = generated_world(tmp_path, checks=(index_check,))
    w.scenarios(ADD_TEST_FILE)
    w.objective()
    w.run_until(w.status_is(TaskStatus.REVIEWING))

    # The kernel reviews only inside a task's scope, so r1 became r2 with the declared output added, before any
    # attempt; the builder was launched once, for r2.
    r1, r2 = sorted((t for t in w.store.read_tasks() if t.task_id == OBJ), key=lambda t: t.revision)
    assert r1.allowed_paths == ("pkg",) and r2.allowed_paths == ("pkg", INDEX) and r2.kind is TaskKind.BUILD
    assert w.store.read_task_state(OBJ, 1).status is TaskStatus.OBSOLETE
    assert [a.task_revision for a in w.store.read_attempts(OBJ)] == [2] and w.invocations() == 1
    # The builder was told the file is the loop's, and its allowed paths do not include it.
    prompt = (w.state / "prompt.0.txt").read_text()
    allowed = prompt.split("ALLOWED PATHS")[1].split("\n\n")[0]
    assert "- pkg" in allowed and INDEX not in allowed
    assert "GENERATED BY CLIVE" in prompt and f"- {INDEX} (generator pkg-index)" in prompt

    [result] = w.store.read_results()
    candidate = result.result_sha
    worker_commit = _git(w.repo, "rev-parse", f"{candidate}^")
    # the candidate is the loop's own commit on top of the builder's, changing exactly the declared output
    assert _git(w.repo, "log", "-1", "--format=%an <%ae>%n%s", candidate) == \
        "CLIVE loop <loop@clive.invalid>\nRegenerate generated files (loop)"
    assert _git(w.repo, "diff", "--name-only", worker_commit, candidate) == INDEX
    assert "pkg/test_new.py" in _git(w.repo, "diff", "--name-only", w.base, worker_commit)
    assert _git(w.repo, "show", f"{candidate}:{INDEX}") == "# pkg index\n- pkg/hello.txt\n- pkg/test_new.py"
    assert set(result.changed_paths) == {"pkg/hello.txt", "pkg/test_new.py", INDEX}
    assert _git(w.repo, "rev-parse", "clive/objective/demo") == candidate
    # CLIVE's own checks ran on that commit, and passed only because the index was regenerated
    attempt = max(w.store.read_attempts(OBJ), key=lambda a: a.fencing_token)
    evidence = tmp_path / "runtime" / "evidence" / attempt.attempt_id
    check = json.loads((evidence / "check-index.json").read_text())
    assert check["head"] == candidate and check["exit_code"] == 0
    generated = json.loads((evidence / "generated.json").read_text())
    assert generated["regenerated"] == [INDEX] and generated["candidate"] == candidate
    assert generated["worker_head"] == worker_commit and generated["declared_at"] == w.base
    names = [e.evidence_name for e in w.store.read_events(OBJ, attempt.attempt_id) if e.kind is EventKind.EVIDENCE]
    assert "generated" in names and names.index("generated") < names.index("check-index")
    run = json.loads((evidence / "generate-pkg-index.json").read_text())
    assert run["argv"] == [sys.executable, "tools/gen_index.py"] and run["changed"] == [INDEX]
    # the reviewer is told, and the status says which files the loop regenerated for this candidate
    packet = (w.store.root / w.store.read_dispatches(OBJ, attempt.attempt_id)[-1].packet_path).read_text()
    assert "## Files the loop regenerated on this candidate" in packet and f"- `{INDEX}`" in packet
    assert w.dispatcher().status()[0]["generated"] == [INDEX]
    w.reviewer.answers.append(lambda ctx: review(ctx))
    w.run_until(lambda: w.stage() == "COMPLETE")


def test_an_output_already_up_to_date_gets_no_loop_commit(tmp_path):
    w = generated_world(tmp_path)
    w.scenarios({"edits": [["pkg/hello.txt", "hello\n"]]})
    w.objective()
    w.run_until(w.status_is(TaskStatus.REVIEWING))
    [result] = w.store.read_results()
    assert _git(w.repo, "log", "-1", "--format=%an", result.result_sha).startswith("CLIVE worker")
    assert result.changed_paths == ("pkg/hello.txt",)
    assert w.dispatcher().status()[0]["generated"] == []


def test_a_builders_own_edit_of_a_generated_file_is_replaced_by_the_generators_output(tmp_path):
    w = generated_world(tmp_path)
    w.scenarios({"edits": [["pkg/hello.txt", "hello\n"], [INDEX, "hand-written, and wrong\n"]]})
    w.objective()
    w.run_until(w.status_is(TaskStatus.REVIEWING))
    [result] = w.store.read_results()
    assert _git(w.repo, "show", f"{result.result_sha}:{INDEX}") == INDEX_BASE.strip()
    assert INDEX not in result.changed_paths          # back to the base's generated content: no change at all


def test_a_builders_edit_of_an_output_its_generator_does_not_write_is_refused_never_admitted(tmp_path):
    """The b577bc97 re-pin review, F-01: a generator that exits 0 without writing its output must not turn the
    builder's own bytes there into "the generator's output", which the scope check then admits. The outputs are
    cleared from the generator's copy first, so an output it does not write is refused."""
    silent = {**PKG_INDEX, "argv": ["{python}", "-c", "pass"]}             # succeeds, writes nothing
    w = generated_world(tmp_path, generators=(silent,))
    w.scenarios({"edits": [["pkg/hello.txt", "hello\n"], [INDEX, "the builder's own words, out of scope\n"]]})
    w.objective()
    w.run_until(w.status_is(TaskStatus.BLOCKED))
    assert not w.store.read_results()                                        # nothing admitted, ever
    first = w.store.read_attempts(OBJ)[0]
    cancelled = [e.note for e in w.store.read_events(OBJ, first.attempt_id) if e.kind is EventKind.CANCELLED]
    assert f"the generator pkg-index did not write {INDEX} as a regular file" in cancelled[0]
    assert "every declared output must be written by its generator" in cancelled[0]


def test_an_output_path_the_builder_turned_into_a_link_is_refused_and_nothing_it_names_is_touched(tmp_path):
    outside = tmp_path / "outside"
    outside.mkdir()
    (outside / "INDEX.md").write_text("not the tree's\n")
    w = generated_world(tmp_path)
    w.scenarios({"edits": [["pkg/hello.txt", "hello\n"]], "exec": []})
    w.objective()
    real_export = w.dispatcher().workspaces.export

    def export_with_a_linked_docs(ws, head, target):
        tree = real_export(ws, head, target)
        shutil.rmtree(tree / "docs")
        os.symlink(outside, tree / "docs")                                 # docs/ now names a folder elsewhere
        return tree

    d = w.dispatcher()
    d.workspaces.export = export_with_a_linked_docs
    w.run_until(w.status_is(TaskStatus.BLOCKED), dispatcher=d)
    assert (outside / "INDEX.md").read_text() == "not the tree's\n"         # never followed, never removed
    first = w.store.read_attempts(OBJ)[0]
    cancelled = [e.note for e in w.store.read_events(OBJ, first.attempt_id) if e.kind is EventKind.CANCELLED]
    assert f"has no plain file where the generator pkg-index writes {INDEX}" in cancelled[0]
    assert "docs is not a directory on the way" in cancelled[0]


def test_a_link_at_the_output_itself_is_refused_and_left_exactly_as_it_was(tmp_path):
    """The 159b4fcc re-pin review, F-01: a link where the generator writes is never removed, only refused."""
    outside = tmp_path / "outside.md"
    outside.write_text("not the tree's\n")
    w = generated_world(tmp_path)
    w.scenarios({"edits": [["pkg/hello.txt", "hello\n"]], "exec": []})
    w.objective()
    real_export = w.dispatcher().workspaces.export
    seen: list[Path] = []

    def export_with_a_linked_index(ws, head, target):
        tree = real_export(ws, head, target)
        (tree / INDEX).unlink()
        os.symlink(outside, tree / INDEX)                                  # docs/INDEX.md now names a file elsewhere
        seen.append(tree / INDEX)
        return tree

    d = w.dispatcher()
    d.workspaces.export = export_with_a_linked_index
    w.run_until(w.status_is(TaskStatus.BLOCKED), dispatcher=d)
    assert outside.read_text() == "not the tree's\n"                        # never followed, never written
    assert seen and all(p.is_symlink() and os.readlink(p) == str(outside) for p in seen)  # never removed
    first = w.store.read_attempts(OBJ)[0]
    cancelled = [e.note for e in w.store.read_events(OBJ, first.attempt_id) if e.kind is EventKind.CANCELLED]
    assert f"has no plain file where the generator pkg-index writes {INDEX}" in cancelled[0]
    assert f"{INDEX} is a link, not a file" in cancelled[0]


def test_clearing_an_output_removes_a_regular_file_and_nothing_else(tmp_path):
    from app.orchestrator.generated import clear_output

    (tmp_path / "docs").mkdir()
    (tmp_path / "docs" / "INDEX.md").write_text("the builder's\n")
    assert clear_output(tmp_path, "docs/INDEX.md") is None and not (tmp_path / "docs" / "INDEX.md").exists()
    assert clear_output(tmp_path, "docs/INDEX.md") is None                 # already gone: the generator makes it

    target = tmp_path / "target.md"
    target.write_text("kept\n")
    os.symlink(target, tmp_path / "docs" / "INDEX.md")
    assert clear_output(tmp_path, "docs/INDEX.md") == "docs/INDEX.md is a link, not a file"
    assert (tmp_path / "docs" / "INDEX.md").is_symlink() and target.read_text() == "kept\n"
    (tmp_path / "docs" / "INDEX.md").unlink()

    os.symlink(tmp_path / "nowhere", tmp_path / "docs" / "INDEX.md")       # a dangling link is still a link
    assert clear_output(tmp_path, "docs/INDEX.md") == "docs/INDEX.md is a link, not a file"
    assert (tmp_path / "docs" / "INDEX.md").is_symlink()
    (tmp_path / "docs" / "INDEX.md").unlink()

    os.mkfifo(tmp_path / "docs" / "INDEX.md")
    assert clear_output(tmp_path, "docs/INDEX.md") == "docs/INDEX.md is not a regular file"
    assert (tmp_path / "docs" / "INDEX.md").exists()
    (tmp_path / "docs" / "INDEX.md").unlink()

    (tmp_path / "docs" / "INDEX.md").mkdir()
    assert clear_output(tmp_path, "docs/INDEX.md") == "docs/INDEX.md is a directory, not a file"
    assert (tmp_path / "docs" / "INDEX.md").is_dir()
    for bad in ("", "docs/../x", "/abs", "docs//INDEX.md"):
        assert "is not a plain repository path" in clear_output(tmp_path, bad)


def test_a_failing_generator_refuses_the_candidate_and_the_retry_is_shown_its_output(tmp_path):
    broken = {**PKG_INDEX, "argv": ["{python}", "-c", "import sys; print('generator exploded'); sys.exit(3)"]}
    w = generated_world(tmp_path, generators=(broken,))
    w.scenarios(ADD_TEST_FILE)
    w.objective()
    w.run_until(w.status_is(TaskStatus.BLOCKED))
    assert not w.store.read_results()
    first = w.store.read_attempts(OBJ)[0]
    cancelled = [e.note for e in w.store.read_events(OBJ, first.attempt_id) if e.kind is EventKind.CANCELLED]
    assert "the generator pkg-index failed" in cancelled[0] and "(exit 3)" in cancelled[0]
    retry = (w.state / "prompt.1.txt").read_text()
    assert "FAILED GENERATOR `generate-pkg-index`" in retry and "generator exploded" in retry


# ---------------------------------------------------------------- what the loop never does

def test_a_generator_declared_only_in_the_candidate_is_never_run(tmp_path, monkeypatch):
    """Read from the task's base, never from the candidate: here the declaration is taken out of the protected
    list and put in the objective's scope, so the candidate's own declaration is accepted as a change, and its
    generator still never runs; the base's does."""
    sentinel = tmp_path / "candidate-generator-ran"
    monkeypatch.setattr(objectives_module, "PROTECTED_PATHS",
                        tuple(p for p in PROTECTED_PATHS if p != DECLARATION))
    w = generated_world(tmp_path)
    planted = declaration(PKG_INDEX, {"name": "planted", "argv": ["/bin/sh", "-c", f"touch {sentinel}"], "cwd": ".",
                                      "outputs": ["docs/planted.txt"]})
    w.scenarios({"edits": [["pkg/hello.txt", "hello\n"], ["pkg/test_new.py", "x = 1\n"], [DECLARATION, planted]]})
    w.objective(allowed_paths=("pkg", DECLARATION))
    w.run_until(w.status_is(TaskStatus.REVIEWING))
    [result] = w.store.read_results()
    assert not sentinel.exists()                                  # the candidate's generator never ran
    assert DECLARATION in result.changed_paths                    # though its declaration is in the candidate
    assert "- pkg/test_new.py" in _git(w.repo, "show", f"{result.result_sha}:{INDEX}")   # the base's generator ran
    evidence = tmp_path / "runtime" / "evidence" / result.attempt_id
    assert sorted(p.name for p in evidence.glob("generate-*.json")) == ["generate-pkg-index.json"]


def test_a_candidate_that_changes_the_declaration_is_refused_before_any_generator_runs(tmp_path):
    sentinel = tmp_path / "candidate-generator-ran"
    w = generated_world(tmp_path)
    planted = declaration({"name": "planted", "argv": ["/bin/sh", "-c", f"touch {sentinel}"], "cwd": ".",
                           "outputs": ["docs/planted.txt"]})
    w.scenarios({"edits": [["pkg/hello.txt", "hello\n"], [DECLARATION, planted]]})
    w.objective()
    w.run_until(w.status_is(TaskStatus.BLOCKED))
    assert not w.store.read_results() and not sentinel.exists()
    first = w.store.read_attempts(OBJ)[0]
    cancelled = [e.note for e in w.store.read_events(OBJ, first.attempt_id) if e.kind is EventKind.CANCELLED][0]
    assert "changes protected paths" in cancelled and DECLARATION in cancelled
    assert not list((tmp_path / "runtime" / "evidence" / first.attempt_id).glob("generate-*.json"))


def test_a_generator_that_touches_an_undeclared_path_blocks_and_nothing_it_wrote_is_committed(tmp_path):
    sneaky = GENERATOR + 'pathlib.Path("pkg/hello.txt").write_text("rewritten by the generator\\n")\n' \
                         'pathlib.Path("pkg/extra.txt").write_text("new\\n")\n'
    w = generated_world(tmp_path, extra={"tools/gen_index.py": sneaky})
    w.scenarios(ADD_TEST_FILE)
    w.objective()
    w.run_until(w.status_is(TaskStatus.BLOCKED))
    reason = w.state_of().blocker_reason
    assert "the generator pkg-index changed file(s) it does not declare" in reason
    assert "pkg/extra.txt" in reason and "pkg/hello.txt" in reason and "discarded" in reason
    assert not w.store.read_results()
    attempt = w.store.read_attempts(OBJ)[-1]
    ws = tmp_path / "workers" / OBJ / attempt.attempt_id
    gd = ws.parent / f"{attempt.attempt_id}.git"
    head_tree = _git(gd, f"--git-dir={gd}", "ls-tree", "-r", "--name-only", "HEAD").splitlines()
    assert "pkg/extra.txt" not in head_tree and not (ws / "pkg" / "extra.txt").exists()
    assert (ws / "pkg" / "hello.txt").read_text() == "hello\n"
    assert _git(gd, f"--git-dir={gd}", "log", "-1", "--format=%an", "HEAD").startswith("CLIVE worker")


@pytest.mark.parametrize("output", [".github/workflows/acceptance.yml",
                                    "crooks-assistant/app/orchestrator/dispatcher.py", DECLARATION])
def test_a_protected_output_is_refused_before_any_builder_or_generator_runs(tmp_path, output):
    sentinel = tmp_path / "generator-ran"
    protected = {"name": "bad", "argv": ["/bin/sh", "-c", f"touch {sentinel}"], "cwd": ".", "outputs": [output]}
    w = generated_world(tmp_path, generators=(PKG_INDEX, protected))
    w.scenarios(ADD_TEST_FILE)
    w.objective()
    w.run_until(w.status_is(TaskStatus.BLOCKED))
    reason = w.state_of().blocker_reason
    assert "declares output(s) on protected path(s)" in reason and output in reason
    assert w.invocations() == 0 and not sentinel.exists() and not w.store.read_attempts(OBJ)
    assert len([t for t in w.store.read_tasks() if t.task_id == OBJ]) == 1     # nothing widened onto it


@pytest.mark.parametrize("content", ["not json", json.dumps({"schema": "clive.generated_files.v1"}),
                                     declaration({**PKG_INDEX, "cwd": "../outside"}),
                                     declaration({**PKG_INDEX, "outputs": ["/etc/passwd"]}),
                                     declaration(PKG_INDEX, {**PKG_INDEX, "name": "twice"})])
def test_a_declaration_the_loop_will_not_run_blocks_before_a_builder_is_spent(tmp_path, content):
    w = generated_world(tmp_path)
    commit_base(w, {DECLARATION: content})
    w.scenarios(ADD_TEST_FILE)
    w.objective()
    w.run_until(w.status_is(TaskStatus.BLOCKED))
    assert "is refused" in w.state_of().blocker_reason and w.invocations() == 0


def test_without_a_declaration_at_the_base_nothing_is_generated_or_widened(tmp_path):
    w = World(tmp_path)
    w.scenarios(ADD_TEST_FILE)
    w.objective()
    w.run_until(w.status_is(TaskStatus.REVIEWING))
    assert [t.revision for t in w.store.read_tasks() if t.task_id == OBJ] == [1]
    [result] = w.store.read_results()
    assert not list((tmp_path / "runtime" / "evidence" / result.attempt_id).glob("generate-*.json"))
    assert w.dispatcher().status()[0]["generated"] == []


# ---------------------------------------------------------------- the repository's own declaration

REPO_ROOT = Path(__file__).resolve().parents[2]
TOOL_MATRIX = "crooks-assistant/docs/phase4/TOOL_MATRIX.md"


def test_the_repository_declares_the_tool_matrix_as_make_tool_matrix_writes_it_and_protects_the_declaration():
    from app.orchestrator.generated import PYTHON, parse_generators

    assert DECLARATION in PROTECTED_PATHS and "crooks-assistant/app/orchestrator/generated.py" in PROTECTED_PATHS
    [tool_matrix] = parse_generators((REPO_ROOT / DECLARATION).read_bytes())
    assert tool_matrix.name == "tool-matrix" and tool_matrix.cwd == "crooks-assistant"
    assert tool_matrix.outputs == (TOOL_MATRIX,)
    assert tool_matrix.argv[0] == PYTHON and "tool_matrix.write()" in tool_matrix.argv[-1]
    assert not objectives_module.protected_paths_in(tool_matrix.outputs)


def test_the_declared_tool_matrix_generator_reproduces_the_checked_in_document_on_a_copy(tmp_path):
    """The declaration runs as written (its cwd, its sys.path, its argv) and writes exactly its output. On a copy of
    the checked-in tree, never on it; the byte-for-byte pin is tests/test_tool_matrix.py's."""
    from app.orchestrator.generated import changed_files, parse_generators, tree_manifest

    [tool_matrix] = parse_generators((REPO_ROOT / DECLARATION).read_bytes())
    listed = subprocess.run(["git", "ls-files", "-z", "--", "crooks-assistant"], cwd=REPO_ROOT, capture_output=True,
                            check=True).stdout.decode().split("\0")
    copy = tmp_path / "tree"
    for rel in filter(None, listed):
        source = REPO_ROOT / rel
        if source.is_file() and not source.is_symlink():
            (copy / rel).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, copy / rel)
    before = tree_manifest(copy)
    proc = subprocess.run(list(tool_matrix.command(sys.executable)), cwd=copy / tool_matrix.cwd, capture_output=True,
                          text=True, timeout=tool_matrix.timeout_s,
                          env={"PATH": os.environ.get("PATH", "/usr/bin:/bin"), "HOME": str(tmp_path),
                               "LANG": "C.UTF-8", "PYTHONDONTWRITEBYTECODE": "1"})
    assert proc.returncode == 0, proc.stderr[-2000:]
    assert set(changed_files(before, tree_manifest(copy))) <= {TOOL_MATRIX}
    assert (copy / TOOL_MATRIX).read_bytes() == (REPO_ROOT / TOOL_MATRIX).read_bytes()
